version: '3'
services:
  postgres:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - matcha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
  
  go:
    container_name: goapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/usr/src/app
    networks:
      - matcha
    depends_on:
      postgres:
        condition: service_healthy

  reactjs:
    container_name: reactapp
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend/app:/usr/src/app
    networks:
      - matcha
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
    name: go-init-docker-db
  goapi:
    name: goapi
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' 
      device: '~/data/go'
  reactapp:
    name: reactapp
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' 
      device: '~/data/reactapp'

networks:
  matcha:
    name: matcha